# -*- coding: utf-8 -*-
"""Potencial Stock Screener

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XRq4xJMEbkYttDayxN1CWBgbT3Y8NJx8
"""

#!pip install yfinance
#!pip install requests pandas
#!pip install dotenv

import requests
import pandas as pd
import re
from datetime import datetime
from bs4 import BeautifulSoup
import os
import requests
from datetime import datetime, timedelta

FINNHUB_API_KEY=os.getenv("FINNHUB_API_KEY")
API_KEY = os.getenv("API_KEY")
CX = os.getenv("CX")
BOT_TOKEN = os.getenv("BOT_TOKEN")
SIGNAL_CHANNEL = os.getenv("SIGNAL_CHANNEL")
NEWS_CHANNEL = os.getenv("NEWS_CHANNEL")
STOCK_FILE = os.getenv("STOCK_FILE")
PORTFOLIO_FILE = os.getenv("PORTFOLIO_FILE")
SIGNALS_FILE = os.getenv("SIGNALS_FILE")

# 📌 Поисковые запросы
current_month = datetime.now().strftime("%B")
current_year = datetime.now().year

queries = [
    f"Top stocks to buy {current_month} {current_year}",
    f"Best stocks to invest in {current_month} {current_year}",
    f"Growth stocks to buy now {current_year}",
    "Best stocks to buy now",
]

# 📥 Загрузка предыдущих данных, если есть
try:
    df_old = pd.read_csv(PORTFOLIO_FILE)
except FileNotFoundError:
    df_old = pd.DataFrame(columns=["ticker", "date", "source", "link"])
existing = set(df_old["ticker"])
new_data = []

# 🔍 Поиск и парсинг
for query in queries:
    print(f"🔍 Поиск: {query}")
    params = {
        "key": API_KEY,
        "cx": CX,
        "q": query,
        "num": 10,
    }
    response = requests.get("https://www.googleapis.com/customsearch/v1", params=params)
    response.raise_for_status()
    data = response.json()

    for item in data.get("items", []):
        title = item.get("title", "")
        snippet = item.get("snippet", "")
        link = item.get("link", "")
        source = re.sub(r"https?://(www\.)?", "", link).split("/")[0]

        # 🔎 Попытка извлечь тикеры (всё в верхнем регистре, от 1 до 5 букв)
        tickers = set(re.findall(r"\b[A-Z]{1,5}\b", title + " " + snippet))

        # Фильтр потенциальных тикеров — можно улучшить
        tickers = [t for t in tickers if t.isalpha() and 1 <= len(t) <= 5]

        for ticker in tickers:
            if ticker not in existing:
                new_data.append({
                  "ticker": ticker,
                  "date": datetime.now().strftime("%Y-%m-%d"),
                  "source": source,
                  "link": link
                })
# === 2. 🚀 SPACInsider ===
SPAC_FILE = "SPAC.csv"
new_data = []

# Загрузка тикеров из SPAC.csv
try:
    df_spac = pd.read_csv(SPAC_FILE)
    tickers = df_spac["Company"].dropna().unique()

    for ticker in tickers:
        ticker = ticker.strip().upper()
        if ticker not in existing:
            new_data.append({
                "ticker": ticker,
                "date": datetime.now().strftime("%Y-%m-%d"),
                "source": "SPAC",
                "link": "https://www.spacinsider.com/stats/"
            })
            existing.add(ticker)

    if new_data:
        df_all = pd.concat([df_old, pd.DataFrame(new_data)], ignore_index=True)
        df_all.to_csv(PORTFOLIO_FILE, index=False)
        print(f"✅ Добавлено SPAC тикеров: {len(new_data)}")
    else:
        print("ℹ️ Новых SPAC тикеров не найдено.")

except Exception as e:
    print(f"⚠️ Ошибка загрузки SPAC из файла: {e}")

# === 3. 💊 FDA Calendar (из fda_updated.csv) ===
try:
    fda_df = pd.read_csv("fda_calendar.csv")
    fda_df["Catalyst Date"] = pd.to_datetime(fda_df["Catalyst Date"], errors="coerce")

    for _, row in fda_df.iterrows():
        event_date = row["Catalyst Date"]
        if pd.isna(event_date):
            continue
        if 0 <= (event_date.date() - datetime.now().date()).days <= 30:
            ticker = str(row["Company"]).strip()
            key = ticker
            if key not in existing:
                new_data.append({
                    "ticker": ticker,
                    "date": datetime.now().strftime("%Y-%m-%d"),
                    "source": "FDA",
                    "link": f"https://finance.yahoo.com/quote/{ticker}"
                })
                existing.add(key)
except Exception as e:
    print(f"⚠️ Ошибка при загрузке FDA CSV: {e}")

# 📦 Сохраняем
if new_data:
    df_new = pd.DataFrame(new_data)
    df_total = pd.concat([df_old, df_new], ignore_index=True)
    df_total.to_csv(PORTFOLIO_FILE, index=False)
    print(f"✅ Сохранено новых записей: {len(new_data)}")
else:
    print("ℹ️ Нет новых тикеров для добавления.")

# === Загрузка API ключа
TARGET_DAYS = 20

def is_liquid_stock(symbol, api_key, min_market_cap=1):
    """Фильтрует по капитализации и бирже"""
    url = f"https://finnhub.io/api/v1/stock/profile2?symbol={symbol}&token={api_key}"
    try:
        res = requests.get(url,timeout=5).json()
        market_cap = res.get("marketCapitalization", 0)
        exchange = res.get("exchange", "")
        print(f"⚠️ {symbol}: кап={market_cap} < {min_market_cap} exc {exchange}")
        if market_cap and market_cap >= min_market_cap and exchange in ["NASDAQ NMS - GLOBAL MARKET", "NEW YORK STOCK EXCHANGE, INC."]:
            return True
    except:
        pass
    return False

# === Загрузка существующих данных
if os.path.exists(PORTFOLIO_FILE):
    df_existing = pd.read_csv(PORTFOLIO_FILE)
else:
    df_existing = pd.DataFrame(columns=["ticker", "date", "source", "link"])

existing_tickers = set(df_existing["ticker"].dropna().tolist())

# === Даты для фильтрации
today = datetime.today().date()
future = today + timedelta(days=TARGET_DAYS)

# === Запрос к Finnhub
url = f"https://finnhub.io/api/v1/calendar/earnings?from={today}&to={future}&token={FINNHUB_API_KEY}"
print(url)
try:
    response = requests.get(url)
    earnings_data = response.json().get("earningsCalendar", [])
except Exception as e:
    print(f"Ошибка при получении данных: {e}")
    earnings_data = []

# === Фильтрация по дате вручную
records = []
for item in earnings_data:
    symbol = item.get("symbol")
    report_date_str = item.get("date")

    if not symbol or not report_date_str:
        continue

    try:
        report_date = datetime.strptime(report_date_str, "%Y-%m-%d").date()
    except:
        continue
    print(f"🔎 {symbol} — отчётность: {report_date} | В интервале? ", end="\n")
    if not (today <= report_date <= future):
        continue

    if symbol not in existing_tickers and is_liquid_stock(symbol, FINNHUB_API_KEY):
        records.append({
            "ticker": symbol,
            "date": today.isoformat(),  # Сохраняем сегодняшнюю дату
            "source": "earnings",
            "link": f"https://finance.yahoo.com/quote/{symbol}"
        })

# === Сохраняем
if records:
    df_new = pd.DataFrame(records)
    df_result = pd.concat([df_existing, df_new], ignore_index=True)
    df_result.to_csv(PORTFOLIO_FILE, index=False)
    print(f"✅ Добавлено {len(df_new)} новых тикеров.")
else:
    print("ℹ️ Новых тикеров с ожидаемой отчетностью не найдено.")

import pandas as pd
from datetime import datetime
import yfinance as yf

# === Путь к файлам ===
tickers_csv = "Stocks.csv"
options_csv = "Options_History.csv"

# === Загружаем тикеры ===
try:
    df_tickers = pd.read_csv(tickers_csv)
    tickers = df_tickers["ticker"].dropna().unique().tolist()
except Exception as e:
    print(f"Ошибка загрузки тикеров: {e}")
    tickers = []

print("# === Загружаем историю опционов (если есть) ===")
if os.path.exists(options_csv):
    df_history = pd.read_csv(options_csv)
else:
    df_history = pd.DataFrame(columns=[
        "date", "ticker", "call_volume", "put_volume",
        "total_volume", "call_open_interest", "put_open_interest"
    ])

today = datetime.now().strftime("%Y-%m-%d")
existing_keys = set(zip(df_history["date"], df_history["ticker"]))
new_data = []

print("# === Получаем опционные данные для каждого тикера ===")
for ticker in tickers:
    key = (today, ticker)
    if key in existing_keys:
        continue  # уже есть в истории

    try:
        t = yf.Ticker(ticker)
        expirations = t.options
        if not expirations:
            continue
        chain = t.option_chain(expirations[0])
        calls = chain.calls
        puts = chain.puts

        call_volume = calls["volume"].sum()
        put_volume = puts["volume"].sum()
        call_oi = calls["openInterest"].sum()
        put_oi = puts["openInterest"].sum()

        new_data.append({
            "date": today,
            "ticker": ticker,
            "call_volume": call_volume,
            "put_volume": put_volume,
            "total_volume": call_volume + put_volume,
            "call_open_interest": call_oi,
            "put_open_interest": put_oi
        })

        print(f"✅ {ticker}: vol={call_volume+put_volume}, OI={call_oi+put_oi}")

    except Exception as e:
        print(f"⚠️ Ошибка по {ticker}: {e}")

print("# === Сохраняем данные ===")
if new_data:
    df_new = pd.DataFrame(new_data)
    df_full = pd.concat([df_history, df_new], ignore_index=True)
    df_full.to_csv(options_csv, index=False)
    print(f"\n✅ Добавлено записей: {len(df_new)} → сохранено в {options_csv}")
else:
    print("ℹ️ Нет новых данных для записи.")

import pandas as pd
import requests
import uuid
from datetime import datetime, timedelta
import yfinance as yf

print("# === Telegram отправка")
def send_telegram_message(text, chat_id, reply_to=None):
    payload = {
        "chat_id": chat_id,
        "text": text,
        "parse_mode": "HTML"
    }
    if reply_to:
        payload["reply_to_message_id"] = reply_to
    resp = requests.post(f"https://api.telegram.org/bot{BOT_TOKEN}/sendMessage", data=payload)
    return resp.json()["result"] if resp.ok else None

def forward_telegram_message(from_chat_id, message_id, to_chat_id):
    url = f"https://api.telegram.org/bot{BOT_TOKEN}/forwardMessage"
    payload = {
        "chat_id": to_chat_id,
        "from_chat_id": from_chat_id,
        "message_id": int(message_id)
    }
    resp = requests.post(url, data=payload)
    return resp.json()["result"] if resp.ok else None

# === Чтение и очистка старых сигналов
def load_signals():
    if os.path.exists(SIGNALS_FILE):
        df = pd.read_csv(SIGNALS_FILE)
        df["date_sent"] = pd.to_datetime(df["date_sent"], errors='coerce')
        df["last_checked"] = pd.to_datetime(df["last_checked"], errors='coerce')
        return df
    else:
        return pd.DataFrame(columns=["id", "ticker", "date_sent", "signal_type", "price_entry", "max_profit", "last_checked", "signal_url"])

def save_signals(df):
    df.to_csv(SIGNALS_FILE, index=False)

# === Отправка сигналов
def compute_signals(df, window_days=5, min_vol=1000, min_oi=500, min_ratio=2):
    signals = []
    tickers = df["ticker"].unique()

    for ticker in tickers:
        df_t = df[df["ticker"] == ticker].copy()
        df_t["date"] = pd.to_datetime(df_t["date"], errors='coerce')
        df_t = df_t.dropna(subset=["date", "total_volume", "call_open_interest", "put_open_interest"])
        df_t = df_t.sort_values("date").tail(window_days)

        if len(df_t) < window_days:
            continue

        volumes = df_t["total_volume"].values
        calls = df_t["call_open_interest"].values
        puts = df_t["put_open_interest"].values
        ratios = [c/p if p > 0 else float('inf') for c, p in zip(calls, puts)]

        if (
            volumes[-1] > volumes[0] and
            calls[-1] > calls[0] and
            ratios[-1] > min_ratio and
            volumes[-1] > min_vol and
            calls[-1] > min_oi
        ):
            signals.append({
                "ticker": ticker,
                "volume_trend": f"{int(volumes[0])} → {int(volumes[-1])}",
                "oi_trend": f"{int(calls[0])} → {int(calls[-1])}",
                "ratio": round(ratios[-1], 2)
            })

    return signals

def send_signals():
    try:
        df = pd.read_csv(STOCK_FILE)
        df = df.dropna(subset=["total_volume", "call_open_interest", "put_open_interest"])
        df["total_volume"] = pd.to_numeric(df["total_volume"], errors='coerce')
        df["call_open_interest"] = pd.to_numeric(df["call_open_interest"], errors='coerce')
        df["put_open_interest"] = pd.to_numeric(df["put_open_interest"], errors='coerce')

        signals = compute_signals(df)
        if not signals:
            print("🚫 Сигналов по динамике активности не найдено.")
            return

        all_signals = load_signals()
        new_rows = []

        for s in signals:
            ticker = s["ticker"]
            signal_type = "BUY"

            if ((all_signals["ticker"] == ticker) & (all_signals["signal_type"] == signal_type)).any():
                print(f"⏩ Уже отправлен ранее: {ticker}")
                continue

            entry_price = yf.Ticker(ticker).history(period="1d")["Close"][-1]
            signal_id = str(uuid.uuid4())[:8]
            today = datetime.now().strftime("%Y-%m-%d")
            url = f"https://t.me/{SIGNAL_CHANNEL.strip('@')}"  # можно заменить на ссылку на конкретный пост

            msg = (
                f"📊 Сигнал: {ticker}\n"
                f"Объём: {s['volume_trend']}\n"
                f"Call OI: {s['oi_trend']}\n"
                f"Call/Put: {s['ratio']}"
            )

            result = send_telegram_message(msg, SIGNAL_CHANNEL)

            if result:
                message_id = result["message_id"]
                channel_username = SIGNAL_CHANNEL.strip("@")
                signal_url = f"https://t.me/{channel_username}/{message_id}"
                print(f"📤 Отправлено: {ticker}")
                new_rows.append({
                    "id": signal_id,
                    "ticker": ticker,
                    "date_sent": today,
                    "signal_type": signal_type,
                    "price_entry": entry_price,
                    "max_profit": 0.0,
                    "last_checked": today,
                    "signal_url": signal_url,
                    "message_id": message_id  # 💥 иначе потом не будет reply
                })

        if new_rows:
            all_signals = pd.concat([all_signals, pd.DataFrame(new_rows)], ignore_index=True)
            save_signals(all_signals)

    except Exception as e:
        print(f"❌ Ошибка: {e}")

# === Мониторинг прибыли и удаление убыточных
def drop_from_csv(filepath, tickers, column="ticker"):
    if os.path.exists(filepath):
        df = pd.read_csv(filepath)
        df = df[~df[column].isin(tickers)]
        df.to_csv(filepath, index=False)

def monitor_signals():
    if not os.path.exists(SIGNALS_FILE):
        return

    df = load_signals()
    updated = []
    dropped = []

    for _, row in df.iterrows():
        ticker = row["ticker"]
        entry = row["price_entry"]
        max_profit = row["max_profit"]
        last_check = pd.to_datetime(row["last_checked"])
        message_id = int(row["message_id"])

        if datetime.now() - last_check < timedelta(days=10):
            updated.append(row)
            continue

        try:
            price_now = yf.Ticker(ticker).history(period="1d")["Close"][-1]
            profit_pct = ((price_now - entry) / entry) * 100

            # Обновляем дату проверки
            row["last_checked"] = datetime.now().strftime("%Y-%m-%d")

            # === Условие 1: Первая фиксация прибыли >20%
            if profit_pct >= 20 and max_profit == 0:
                forward = forward_telegram_message(SIGNAL_CHANNEL, message_id, NEWS_CHANNEL)
                if forward:
                    forward_msg_id = forward["message_id"]
                    news_reply = f"🎉 {ticker} вырос более чем на 20%!\n📈 Прибыль: {profit_pct:.2f}%\nПоздравляем всех, кто зашёл!"
                    send_telegram_message(news_reply, NEWS_CHANNEL, reply_to=forward_msg_id)

                # Реплай в канал с сигналом
                reply_signal = f"✅ {ticker} достиг цели +20%!\nТекущая прибыль: {profit_pct:.2f}%"
                send_telegram_message(reply_signal, SIGNAL_CHANNEL, reply_to=message_id)

                row["max_profit"] = profit_pct

            # === Условие 2: Обновление максимума прибыли
            elif profit_pct > max_profit:
                forward = forward_telegram_message(SIGNAL_CHANNEL, message_id, NEWS_CHANNEL)
                if forward:
                    forward_msg_id = forward["message_id"]
                    news_reply = f"📈 {ticker} обновил максимум: +{profit_pct:.2f}%"
                    send_telegram_message(news_reply, NEWS_CHANNEL, reply_to=forward_msg_id)

                # Реплай в канал с сигналом
                reply_signal = f"📈 Новый максимум прибыли по {ticker}: +{profit_pct:.2f}%"
                send_telegram_message(reply_signal, SIGNAL_CHANNEL, reply_to=message_id)

                row["max_profit"] = profit_pct

            # === Условие 3: Прибыль падает → удалить
            elif profit_pct < max_profit:
                print(f"🗑 {ticker} удалён — прибыль упала")
                dropped.append(ticker)
                continue

            updated.append(row)

        except Exception as e:
            print(f"⚠️ Ошибка по {ticker}: {e}")
            updated.append(row)

    save_signals(pd.DataFrame(updated))

    if dropped:
        drop_from_csv(STOCK_FILE, dropped)
        drop_from_csv(PORTFOLIO_FILE, dropped)
        drop_from_csv(SIGNALS_FILE, dropped)
        print(f"🧹 Удалены тикеры: {dropped}")

# === Запуск
print("Отправка сигналов при наличии")
send_signals()
print("Мониторинг сигналов с прибыльным PnL")
monitor_signals()

print("🎯 DONE")


